package sk.uniba.fmph.dcs.game_board;

import org.json.JSONObject;
import sk.uniba.fmph.dcs.stone_age.*;

import java.util.*;

public class CivilizationCardPlace implements InterfaceFigureLocationInternal {
    private final CivilizationCardDeck cardDeck;
    private CivilizationCardPlace nextCardPlace;
    private CivilizationCardPlace previousCardPlace;
    private final int requiredResources;
    private final List<PlayerOrder> placedFigures;
    private CivilizationCard currentCard;
    private boolean isEndOfGame;

    public CivilizationCardPlace(int requiredResources, CivilizationCardDeck cardDeck) {
        this.requiredResources = requiredResources;
        this.cardDeck = cardDeck;
        this.placedFigures = new ArrayList<>();
        this.currentCard = drawCard();
        this.isEndOfGame = false;
    }

    @Override
    public boolean placeFigures(Player player, int figureCount) {
        if (tryToPlaceFigures(player, figureCount) == HasAction.NO_ACTION_POSSIBLE) {
            return false;
        }

        placedFigures.add(player.playerOrder());
        player.playerBoard().takeFigures(1);
        return true;
    }

    /**
        @param player The player attempting to place the figure.
        @param figureCount The number of figures being placed.
        @return The action's status after attempting to place the figure.
    */
    @Override
    public HasAction tryToPlaceFigures(Player player, int figureCount) {
        return (!placedFigures.isEmpty() || figureCount != 1 || !player.playerBoard().hasFigures(figureCount))
                ? HasAction.NO_ACTION_POSSIBLE
                : HasAction.WAITING_FOR_PLAYER_ACTION;
    }

    /**
        @param player The player performing the action.
        @param inputResources The resources provided by the player.
        @param outputResources The resources generated by the action (not used here).
        @return The result of the action (e.g., success or failure).
    */
    @Override
    public ActionResult makeAction(Player player, Collection<Effect> inputResources, Collection<Effect> outputResources) {
        if (inputResources.size() < requiredResources || tryToMakeAction(player) == HasAction.NO_ACTION_POSSIBLE) {
            return ActionResult.FAILURE;
        }

        Effect[] payment = inputResources.stream().limit(requiredResources).toArray(Effect[]::new);
        if (payment.length != requiredResources || !player.playerBoard().takeResources(List.of(payment))) {
            return ActionResult.FAILURE;
        }

        placedFigures.remove(player.playerOrder());
        player.playerBoard().takeFigures(-1);

        for (EndOfGameEffect endEffect : currentCard.getEndOfGameEffectType()) {
            player.playerBoard().giveEndOfGameEffect(List.of(new EndOfGameEffect[]{endEffect}));
        }

        ActionResult actionResult = ActionResult.ACTION_DONE;
        for (ImmediateEffect immediateEffect : currentCard.getImmediateEffectType()) {
            EvaluateCivilizationCardImmediateEffect evaluator = createEffectEvaluator(immediateEffect);
            if (evaluator != null) {
                evaluator.performEffect(player, null);
            }

            if (immediateEffect == ImmediateEffect.ThrowWood || immediateEffect == ImmediateEffect.ThrowClay || immediateEffect == ImmediateEffect.ThrowStone || immediateEffect == ImmediateEffect.ThrowGold) {
                actionResult = ActionResult.ACTION_DONE_WAIT_FOR_TOOL_USE;
            }
        }

        currentCard = null;
        return actionResult;
    }

    /**
        @param player The player choosing to skip the action.
        @return True if the skip was successful, false otherwise.
    */
    @Override
    public boolean skipAction(Player player) {
        if (!placedFigures.contains(player.playerOrder())) {
            return false;
        }

        placedFigures.remove(player.playerOrder());
        player.playerBoard().takeFigures(-1);
        return true;
    }

    /**
        @param player The player attempting to perform the action.
        @return The action's status after attempting.
    */
    @Override
    public HasAction tryToMakeAction(Player player) {
        return (currentCard == null || !placedFigures.contains(player.playerOrder()))
                ? HasAction.NO_ACTION_POSSIBLE
                : HasAction.WAITING_FOR_PLAYER_ACTION;
    }

    /**
        @return True if it's the end of the game, false otherwise. Clears placed figures and updates the active card if needed.
    */
    @Override
    public boolean newTurn() {
        placedFigures.clear();
        if (currentCard == null) {
            CivilizationCardPlace previous = findPreviousCardWithCard();
            if (previous != null) {
                currentCard = previous.currentCard;
                previous.currentCard = null;
            }
        }

        if (requiredResources == 4) {
            refillCards();
        }

        return isEndOfGame;
    }

    private void refillCards() {
        CivilizationCardPlace place = this;
        while (place.nextCardPlace != null) {
            if (place.currentCard == null) {
                place.currentCard = drawCard();
            }
            place = place.nextCardPlace;
        }
    }

    private CivilizationCardPlace findPreviousCardWithCard() {
        CivilizationCardPlace place = this;
        while (place.previousCardPlace != null && place.previousCardPlace.currentCard == null) {
            place = place.previousCardPlace;
        }
        return place.previousCardPlace;
    }

    public String state() {
        Map<String, String> stateMap = new HashMap<>();
        stateMap.put("requiredResources", String.valueOf(requiredResources));
        stateMap.put("placedFigures", placedFigures.toString());
        return new JSONObject(stateMap).toString();
    }

    private CivilizationCard drawCard() {
        Optional<CivilizationCard> optionalCard = cardDeck.getTop();
        if (optionalCard.isEmpty()) {
            isEndOfGame = true;
            return null;
        }
        return optionalCard.get();
    }

    public CivilizationCard getCurrentCard() {
        return currentCard;
    }

    public void setup(CivilizationCardPlace next, CivilizationCardPlace previous) {
        this.nextCardPlace = next;
        this.previousCardPlace = previous;
    }

    public int getRequiredResources() {
        return requiredResources;
    }

    private EvaluateCivilizationCardImmediateEffect createEffectEvaluator(ImmediateEffect immediateEffect) {
        Map<ImmediateEffect, EvaluateCivilizationCardImmediateEffect> effectEvaluatorMap = new HashMap<>();
        effectEvaluatorMap.put(ImmediateEffect.WOOD, new GetSomethingFixed(Effect.WOOD));
        effectEvaluatorMap.put(ImmediateEffect.CLAY, new GetSomethingFixed(Effect.CLAY));
        effectEvaluatorMap.put(ImmediateEffect.STONE, new GetSomethingFixed(Effect.STONE));
        effectEvaluatorMap.put(ImmediateEffect.GOLD, new GetSomethingFixed(Effect.GOLD));
        effectEvaluatorMap.put(ImmediateEffect.FOOD, new GetSomethingFixed(Effect.FOOD));
        effectEvaluatorMap.put(ImmediateEffect.ThrowWood, new GetSomethingThrow(Effect.WOOD));
        effectEvaluatorMap.put(ImmediateEffect.ThrowClay, new GetSomethingThrow(Effect.CLAY));
        effectEvaluatorMap.put(ImmediateEffect.ThrowStone, new GetSomethingThrow(Effect.STONE));
        effectEvaluatorMap.put(ImmediateEffect.ThrowGold, new GetSomethingThrow(Effect.GOLD));
        effectEvaluatorMap.put(ImmediateEffect.CARD, new GetCard(cardDeck));
        effectEvaluatorMap.put(ImmediateEffect.ArbitraryResource, new GetSomethingChoice(1));

        return effectEvaluatorMap.getOrDefault(immediateEffect, null);
    }
}
